[project]
name = "diffrhythm"
version = "1.0.0"
description = ""
readme = "src/diffrhythm/Readme.md"
requires-python = ">=3.12.0,<3.13"
dependencies = [
  "einops>=0.8.1",
  "huggingface-hub>=0.29.3",
  "inflect>=7.5.0",
  "langsegment>=0.3.5",
  "librosa>=0.11.0",
  "llvmlite>=0.44.0",
  "muq>=0.1.0",
  "mutagen>=1.47.0",
  "numpy>=2.1.3",
  "nvidia-cudnn-cu12>=9.8.0.87",
  "nvidia-cusparselt-cu12>=0.7.1",
  "nvidia-nccl-cu12>=2.25.1",
  "phonemizer>=3.3.0",
  "torch>=2.6.0",
  "torchaudio>=2.6.0",
  "torchdiffeq>=0.2.5",
  "torchvision>=0.21.0",
  "unidecode>=1.3.8",
  "x-transformers>=2.1.24",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchaudio = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/diffrhythm"]
